#!/bin/sh
echo " Welcome to isg32's script"
sleep 2
clear
echo " "
echo " "
echo " Installing Brave-Browser..."
echo " "
echo " "
sleep 2

clear

sudo apt install curl

sleep 2

sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

sleep 2

echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sleep 2 

sudo apt update

sleep2

sudo apt install brave-browser
